apiVersion: v1
kind: Service
metadata:
  name: zevrant-backup-service-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zevrant-backup-service-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-backup-service-db
  labels:
    app: zevrant-backup-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-backup-service-db
  template:
    metadata:
      labels:
        app: zevrant-backup-service-db
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: database
          nfs:
            server: nfs-controller.zevrant-services.com
            path: /nfs/exports/backup-$ENVIRONMENT
      nodeSelector:
        architecture: arm
      containers:
        - name: zevrant-backup-service-db
          image: postgres:12
          volumeMounts:
            - name: database
              mountPath: /opt/postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-db-password
                  key: password
            - name: PGDATA
              value: /opt/postgres
            - name: POSTGRES_USER
              value: zevrant
            - name: POSTGRES_DB
              value: backup
          ports:
            - containerPort: 5432

