apiVersion: v1
kind: Service
metadata:
  name: zevrant-backup-service-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zevrant-backup-service-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-backup-service-db-deployment
  annotations:
    iam.amazonaws.com/role: OauthServiceRole
  labels:
    app: zevrant-backup-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-backup-service-db
  template:
    metadata:
      labels:
        app: zevrant-backup-service-db
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: database
          nfs:
            server: 192.168.1.11
            path: /i-data/420aa917/nfs/keys
      nodeSelector:
        architecture: arm
      containers:
        - name: zevrant-backup-service-db
          image: postgres:12
          volumeMounts:
            - name: database
              mountPath: /storage/keys/
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backup-db-password
                  key: password
            - name: PGDATA
              value: /storage/keys/db/$ENVIRONMENT/backup/
            - name: POSTGRES_USER
              value: zevrant
            - name: POSTGRES_DB
              value: backup
          ports:
            - containerPort: 5432

