apiVersion: v1
kind: Service
metadata:
  name: zevrant-backup-service
spec:
  ports:
    - port: 443
      targetPort: 9009
  selector:
    app: zevrant-backup-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-backup-service
  labels:
    app: zevrant-backup-service
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: zevrant-backup-service
  template:
    metadata:
      labels:
        app: zevrant-backup-service
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: backup-service
          nfs:
            server: nfs-controller.zevrant-services.com
            path: /nfs/exports/backup-service-$ENVIRONMENT
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-backup-service
          image: zevrant/zevrant-backup-service:$VERSION
          volumeMounts:
            - name: backup-service
              mountPath: /storage/backups/
          ports:
            - containerPort: 9009
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-backup-service/actuator/health
              port: 9009
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-backup-service/actuator/health
              port: 9009
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-vault-credentials
                  key: password
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup-vault-credentials
                  key: username
          resources:
            requests:
              memory: 2Gi
              cpu: 2000m
            limits:
              memory: 2Gi
              cpu: 2000m

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: zevrant-backup-service
spec:
  behavior:
    scaleUp:
      policies:
        - periodSeconds: 10
          type: Pods
          value: 1
    scaleDown:
      policies:
        - periodSeconds: 10
          type: Pods
          value: 1
  scaleTargetRef:
    kind: Deployment
    name: zevrant-backup-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
