apiVersion: v1
kind: Service
metadata:
  name: zevrant-backup-service
spec:
  ports:
    - port: 443
      targetPort: 9009
  selector:
    app: zevrant-backup-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-backup-service-deployment
  labels:
    app: zevrant-backup-service
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: zevrant-backup-service
  template:
    metadata:
      labels:
        app: zevrant-backup-service
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: backup-service
          nfs:
            server: nfs-controller.zevrant-services.com
            path: /backup-service-$ENVIRONMENT
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-backup-service
          image: zevrant/zevrant-backup-service:$VERSION
          volumeMounts:
            - name: backup-service
              mountPath: /storage/backups/
          ports:
            - containerPort: 9009
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-backup-service/actuator/health
              port: 9009
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-backup-service/actuator/health
              port: 9009
            initialDelaySeconds: 30
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zevrant-backup-service-aws
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zevrant-backup-service-aws
                  key: password
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: 1000m
