server:
  ssl:
    key-store: /opt/acme/certs/zevrant-services.p12
    key-store-type: PKCS12

spring:
  datasource:
    url: 'jdbc:postgresql://zevrant-backup-service-db:5432/backup'
    username: 'zevrant'
    password: ${rds.backup.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://zevrant-services.com/auth/realms/zevrant-services-prod

logging:
  level:
    com.zevrant.services: info
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

zevrant:
  keystore:
    password: /var/zevrant-services/keystore/password
  vault:
    username: /var/zevrant-services/vault/username
    password: /var/zevrant-services/vault/password