server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-backup-service/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}

spring:
  datasource:
    url: 'jdbc:postgresql://zevrant-backup-service-db:5432/backup'
    username: 'zevrant'
    password: ${rds.backup.password}
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://zevrant-keycloak-service/auth/realms/zevrant-services

zevrant:
  services:
    oauth2:
      baseUrl: https://zevrant-oauth2-service